import { useEffect, useMemo, useState } from 'react';
import { Activity, ArrowUpRight, Boxes, Check, ChevronDown, CircleAlert, ClipboardCheck, Clock3, Download, FileSpreadsheet, Layers3, PackageCheck, RefreshCw, ShieldCheck, SlidersHorizontal, Warehouse as WarehouseIcon } from 'lucide-react';
import { calculate, getOrders, isMock } from '../data/api';
import type { OrderLine, Urgency } from '../data/types';

const money = new Intl.NumberFormat('ru-RU');
const urgencyName: Record<Urgency,string> = {critical:'Срочно',soon:'Скоро',planned:'Планово'};
export default function App(){
 const [lines,setLines]=useState<OrderLine[]>([]); const [warehouse,setWarehouse]=useState('Все склады'); const [category,setCategory]=useState('Все категории');
 const [busy,setBusy]=useState(false); const [error,setError]=useState(''); const [approved,setApproved]=useState(false); const [now,setNow]=useState(new Date());
 const warehouses=useMemo(()=>['Все склады',...new Set(lines.map(x=>x.warehouse))],[lines]); const categories=useMemo(()=>['Все категории',...new Set(lines.map(x=>x.category))],[lines]);
 useEffect(()=>{let active=true;getOrders().then(data=>{if(active)setLines(data)}).catch(e=>{if(active)setError(e instanceof Error?e.message:'Не удалось загрузить заказы.')});return()=>{active=false}},[]);
 const filtered=lines.filter(x=>(warehouse==='Все склады'||x.warehouse===warehouse)&&(category==='Все категории'||x.category===category));
 const urgent=filtered.filter(x=>x.urgency==='critical').length; const qty=filtered.reduce((n,x)=>n+x.quantity,0); const ready=filtered.filter(x=>x.reviewed).length;
 const suppliers=Array.from(new Set(filtered.map(x=>x.supplier))).map(name=>({name,count:filtered.filter(x=>x.supplier===name).length,units:filtered.filter(x=>x.supplier===name).reduce((n,x)=>n+x.quantity,0)}));
 const categoriesSummary=Array.from(new Set(filtered.map(x=>x.category))).map(name=>({name,count:filtered.filter(x=>x.category===name).length,units:filtered.filter(x=>x.category===name).reduce((n,x)=>n+x.quantity,0)}));
 async function run(){setBusy(true);setError('');try{const next=await calculate({warehouse:warehouse==='Все склады'?undefined:warehouse,category:category==='Все категории'?undefined:category});setLines(next);setApproved(false);setNow(new Date());}catch(e){setError(e instanceof Error?e.message:'Не удалось выполнить расчёт.');}finally{setBusy(false);}}
 function patch(id:string, updates:Partial<OrderLine>){setLines(prev=>prev.map(x=>x.id===id?{...x,...updates,status:'pending'}:x.status==='approved'?{...x,status:'pending'}:x));setApproved(false);}
 function approve(){if(!filtered.length||filtered.some(x=>!x.reviewed)){setError('Перед подтверждением проверьте и отметьте каждую строку.');return;} setLines(prev=>prev.map(x=>filtered.some(y=>y.id===x.id)?{...x,status:'approved'}:x));setApproved(true);setError('');}
 function exportCsv(){const done=filtered.filter(x=>x.status==='approved');if(!done.length){setError('Сначала подтвердите проверенные строки менеджером.');return;}const cols=['SKU','BOM_ID','WAREHOUSE','SUPPLIER','QUANTITY','UNIT'];const rows=done.map(x=>[x.sku,x.bomId,x.warehouse,x.supplier,String(x.quantity),x.unit]);const csv='\uFEFF'+[cols,...rows].map(r=>r.map(v=>`"${v.replace(/"/g,'""')}"`).join(';')).join('\r\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));a.download=`orders-1c-${new Date().toISOString().slice(0,10)}.csv`;a.click();URL.revokeObjectURL(a.href);}
 return <div className="app-shell"><aside className="sidebar"><a className="brand" href="#"><span className="brand-mark"><Layers3 size={19}/></span><span>Kontur<span className="brand-sub">PROCUREMENT INTELLIGENCE</span></span></a><div className="side-caption">РАБОЧЕЕ ПРОСТРАНСТВО</div><nav><a className="nav-item active"><Boxes size={17}/>Заказы <span className="nav-count">{filtered.length}</span></a><a className="nav-item"><Activity size={17}/>Аналитика</a><a className="nav-item"><WarehouseIcon size={17}/>Склады</a></nav><div className="sidebar-bottom"><span className="status-dot"/>Сервис подключён <span className="version">v0.9</span></div></aside>
 <main className="main"><header className="topbar"><div className="breadcrumb">Закупки <span>/</span> Рекомендации</div><div className="top-actions"><span className="today">{new Intl.DateTimeFormat('ru-RU',{day:'numeric',month:'long',year:'numeric'}).format(now)}</span><div className="avatar">МЗ</div></div></header>
 <div className="content"><div className="heading-row"><div><div className="eyebrow">УПРАВЛЕНИЕ ПОПОЛНЕНИЕМ <span className="live-dot"/></div><h1>Рекомендации к заказу</h1><p className="subtitle">Проверьте потребность, скорректируйте объём и подтвердите заказ вручную.</p></div><button className="primary run-button" onClick={run} disabled={busy}><RefreshCw size={16} className={busy?'spin':''}/>{busy?'Считаем…':'Рассчитать потребность'}</button></div>
 {isMock&&<div className="mock-banner"><CircleAlert size={16}/><span><b>Демо-режим</b> · Синтетические данные для разработки. Подключите API через <code>VITE_API_BASE_URL</code>.</span></div>}
 {error&&<div className="error-banner"><CircleAlert size={17}/>{error}<button onClick={()=>setError('')} aria-label="Закрыть">×</button></div>}
 <section className="filters card"><div className="filter-title"><SlidersHorizontal size={16}/> ПАРАМЕТРЫ РАСЧЁТА</div><label className="select-wrap"><WarehouseIcon size={15}/><select value={warehouse} onChange={e=>setWarehouse(e.target.value)}>{warehouses.map(x=><option key={x}>{x}</option>)}</select><ChevronDown size={14}/></label><label className="select-wrap"><Layers3 size={15}/><select value={category} onChange={e=>setCategory(e.target.value)}>{categories.map(x=><option key={x}>{x}</option>)}</select><ChevronDown size={14}/></label><span className="filter-hint">Фильтры применятся к следующему расчёту</span></section>
 <section className="metrics"><Metric label="ПОЗИЦИЙ К ЗАКАЗУ" value={String(filtered.length).padStart(2,'0')} sub={`${ready} из ${filtered.length} проверено`} icon={<ClipboardCheck/>} accent="green"/><Metric label="ЕДИНИЦ К ЗАКАЗУ" value={money.format(qty)} sub="По текущим рекомендациям" icon={<Boxes/>} accent="blue"/><Metric label="ТРЕБУЮТ ВНИМАНИЯ" value={String(urgent).padStart(2,'0')} sub="Критичный уровень остатка" icon={<CircleAlert/>} accent="orange"/></section>
 <div className="section-head"><div><h2>План пополнения</h2><p>Персональный план на основе актуальных остатков</p></div><div className="head-actions"><span className="updated"><span className="status-dot"/> Обновлено {new Intl.DateTimeFormat('ru-RU',{hour:'2-digit',minute:'2-digit'}).format(now)}</span><button className="quiet-button" onClick={exportCsv}><Download size={15}/>Экспорт 1С</button></div></div>
 <section className="table-card card"><div className="table-toolbar"><div className="tabs"><span className="tab active">Все позиции <b>{filtered.length}</b></span><span className="tab">На проверке <b>{filtered.filter(x=>!x.reviewed).length}</b></span><span className="tab">Подтверждены <b>{filtered.filter(x=>x.status==='approved').length}</b></span></div><form className="search-form" method="get"><label htmlFor="project-search">Search projects</label><div className="join"><input className="input join-item" id="project-search" name="q" type="search" placeholder="SKU или название"/><button className="btn btn-primary join-item" type="submit">Search</button></div></form></div>
 <div className="table-scroll"><table><thead><tr><th>ПОЗИЦИЯ</th><th>ПОСТАВЩИК</th><th>ОСТАТОК / ТРЕНД</th><th>РЕКОМЕНДАЦИЯ</th><th>СРОЧНОСТЬ</th><th>ПРОВЕРКА</th></tr></thead><tbody>{filtered.map(line=><tr key={line.id}><td><div className="product"><div className="product-icon"><PackageCheck size={17}/></div><div><b>{line.product}</b><span>{line.sku} <i>·</i> {line.category}</span></div></div></td><td><span className="supplier-name">{line.supplier}</span><span className="warehouse-name">{line.warehouse}</span></td><td><div className="stock"><b>{line.stock} <small>{line.unit}</small></b><span><Activity size={13}/> {line.monthlyUse}/мес. · {line.leadDays} дн.</span><div className="stock-track"><i style={{width:`${Math.min(100,line.stock/(line.monthlyUse||1)*100)}%`}}/></div></div></td><td><div className="quantity-control"><button aria-label="Уменьшить" onClick={()=>patch(line.id,{quantity:Math.max(0,line.quantity-1)})}>−</button><input type="number" min="0" value={line.quantity} onChange={e=>patch(line.id,{quantity:Math.max(0,Number(e.target.value))})}/><span>{line.unit}</span><button aria-label="Увеличить" onClick={()=>patch(line.id,{quantity:line.quantity+1})}>+</button></div><span className="reason" title={line.justification}>{line.justification}</span></td><td><span className={`urgency ${line.urgency}`}><i/>{urgencyName[line.urgency]}</span></td><td><button className={`review ${line.reviewed?'checked':''}`} onClick={()=>patch(line.id,{reviewed:!line.reviewed})}>{line.reviewed?<Check size={14}/>:<span className="check-empty"/>}{line.reviewed?'Проверено':'Проверить'}</button>{line.status==='approved'&&<span className="approved-mini"><ShieldCheck size={12}/>Подтверждено</span>}</td></tr>)}</tbody></table>{!filtered.length&&<div className="empty">По заданным фильтрам ничего не найдено.</div>}</div>
 <div className="table-footer"><span>Показано {filtered.length} позиций</span><span><Clock3 size={13}/> Данные расчёта: {now.toLocaleTimeString('ru-RU',{hour:'2-digit',minute:'2-digit'})}</span></div></section>
 <div className="lower-grid"><section className="card breakdown"><div className="panel-title"><div><h3>Распределение по категориям</h3><p>Структура объёма заказа</p></div><ArrowUpRight size={17}/></div>{categoriesSummary.slice(0,4).map((c,i)=><div className="break-row" key={c.name}><span className={`break-icon tone-${i}`}><Layers3 size={15}/></span><div className="break-main"><div><b>{c.name}</b><span>{c.count} позиций · {c.units} ед.</span></div><div className="bar"><i style={{width:`${qty?Math.max(6,c.units/qty*100):0}%`}}/></div></div></div>)}</section>
 <section className="card breakdown"><div className="panel-title"><div><h3>Поставщики</h3><p>Сводка рекомендованных заказов</p></div><ArrowUpRight size={17}/></div>{suppliers.map((s,i)=><div className="supplier-row" key={s.name}><div className="supplier-logo">{s.name.slice(11,12)||'П'}</div><div className="supplier-info"><b>{s.name}</b><span>{s.count} позиции · {s.units} ед.</span></div><span className="supplier-arrow"><ArrowUpRight size={15}/></span></div>)}</section></div>
 <section className={`approval ${approved?'done':''}`}><div className="approval-icon">{approved?<ShieldCheck size={21}/>:<ClipboardCheck size={21}/>}</div><div className="approval-copy"><b>{approved?'Рекомендации подтверждены ответственным сотрудником':'Подтверждение менеджера по закупкам'}</b><span>{approved?'Теперь можно выгрузить подтверждённые позиции для 1С. Отправка поставщику не выполняется.':'Проверьте все строки и подтвердите заказ вручную. Это действие фиксирует согласование и открывает экспорт.'}</span></div><button className={approved?'quiet-button':'approve-button'} onClick={approved?exportCsv:approve} disabled={!filtered.length||filtered.some(x=>!x.reviewed)}>{approved?<><FileSpreadsheet size={16}/>Скачать CSV для 1С</>:<><ShieldCheck size={16}/>Подтвердить заказ</>}</button></section>
 <footer><span><ShieldCheck size={14}/> Отправка поставщикам отключена</span><span>Контур закупок <i>·</i> Инструмент планирования</span></footer></div></main></div>
}
function Metric({label,value,sub,icon,accent}:{label:string,value:string,sub:string,icon:React.ReactNode,accent:string}){return <article className="metric card"><div className={`metric-icon ${accent}`}>{icon}</div><div><span className="metric-label">{label}</span><div className="metric-value">{value}</div><span className="metric-sub">{sub}</span></div><ArrowUpRight className="metric-corner" size={15}/></article>}
