import { useEffect, useMemo, useState } from 'react';
import { Activity, ArrowUpRight, Boxes, Check, ChevronDown, CircleAlert, ClipboardCheck, Clock3, Download, FileSpreadsheet, Layers3, PackageCheck, RefreshCw, ShieldCheck, SlidersHorizontal, Warehouse as WarehouseIcon } from 'lucide-react';
import { Badge } from '../components/ui/Badge';
import { BarList } from '../components/ui/BarList';
import { Card } from '../components/ui/Card';
import { approveOrders, calculate, exportOrders, getOrders, isMock, uploadReport } from '../data/api';
import type { OrderLine, Urgency } from '../data/types';

const money = new Intl.NumberFormat('ru-RU');
const urgencyName: Record<Urgency,string> = {critical:'Срочно',soon:'Скоро',planned:'Планово'};
export default function App(){
 const [lines,setLines]=useState<OrderLine[]>([]); const [warehouse,setWarehouse]=useState('Все склады'); const [category,setCategory]=useState('Все категории');
 const [busy,setBusy]=useState(false); const [error,setError]=useState(''); const [exportBusy,setExportBusy]=useState(false); const [now,setNow]=useState(new Date()); const [uploadBusy,setUploadBusy]=useState(false); const [uploadMessage,setUploadMessage]=useState(''); const [dragging,setDragging]=useState(false);
 const warehouses=useMemo(()=>['Все склады',...new Set(lines.map(x=>x.warehouse))],[lines]); const categories=useMemo(()=>['Все категории',...new Set(lines.map(x=>x.category))],[lines]);
 useEffect(()=>{let active=true;getOrders().then(data=>{if(active)setLines(data)}).catch(e=>{if(active)setError(e instanceof Error?e.message:'Не удалось загрузить заказы.')});return()=>{active=false}},[]);
 const filtered=lines.filter(x=>(warehouse==='Все склады'||x.warehouse===warehouse)&&(category==='Все категории'||x.category===category));
 const urgent=filtered.filter(x=>x.urgency==='critical').length; const qty=filtered.reduce((n,x)=>n+x.quantity,0); const ready=filtered.filter(x=>x.reviewed).length; const allApproved=filtered.length>0&&filtered.every(x=>x.status==='approved');
 const suppliers=Array.from(new Set(filtered.map(x=>x.supplier))).map(name=>({name,count:filtered.filter(x=>x.supplier===name).length,units:filtered.filter(x=>x.supplier===name).reduce((n,x)=>n+x.quantity,0)}));
 const categoriesSummary=Array.from(new Set(filtered.map(x=>x.category))).map(name=>({name,count:filtered.filter(x=>x.category===name).length,units:filtered.filter(x=>x.category===name).reduce((n,x)=>n+x.quantity,0)}));
 async function run(){setBusy(true);setError('');try{const next=await calculate({warehouse:warehouse==='Все склады'?undefined:warehouse,category:category==='Все категории'?undefined:category});setLines(next);setNow(new Date());}catch(e){setError(e instanceof Error?e.message:'Не удалось выполнить расчёт.');}finally{setBusy(false);}}
 function patch(id:string, updates:Partial<OrderLine>){setLines(prev=>prev.map(x=>x.id===id&&x.status!=='approved'?{...x,...updates,...('quantity'in updates?{reviewed:false}:{}),status:'pending'}:x));}
 async function approve(){if(!filtered.length||filtered.some(x=>!x.reviewed)){setError('Перед подтверждением проверьте и отметьте каждую строку.');return;}setBusy(true);setError('');try{await approveOrders(filtered);setLines(prev=>prev.map(x=>filtered.some(y=>y.id===x.id)?{...x,status:'approved'}:x));}catch(e){setError(e instanceof Error?e.message:'Не удалось отправить согласование.');}finally{setBusy(false);}}
 async function exportCsv(){if(!allApproved){setError('Сначала подтвердите отображаемые позиции менеджером.');return;}setExportBusy(true);setError('');try{const blob=await exportOrders();const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`orders-1c-${new Date().toISOString().slice(0,10)}.csv`;a.click();window.setTimeout(()=>URL.revokeObjectURL(url),1000);}catch(e){setError(e instanceof Error?e.message:'Не удалось выгрузить файл для 1С.');}finally{setExportBusy(false);}}
 async function handleUpload(file?:File){if(!file)return;if(!/\.(xlsx|xls|csv)$/i.test(file.name)){setError('Поддерживаются файлы XLSX, XLS и CSV.');return;}if(file.size>25*1024*1024){setError('Размер файла превышает лимит 25 МБ.');return;}setUploadBusy(true);setUploadMessage('');setError('');try{await uploadReport(file);setUploadMessage('Файл передан backend для обработки. Запустите расчёт после завершения импорта.');}catch(e){setError(e instanceof Error?e.message:'Не удалось загрузить отчёт.');}finally{setUploadBusy(false);}}
 return <div className="app-shell"><aside className="sidebar"><a className="brand" href="#"><span className="brand-mark"><Layers3 size={19}/></span><span>Kontur<span className="brand-sub">PROCUREMENT INTELLIGENCE</span></span></a><div className="side-caption">РАБОЧЕЕ ПРОСТРАНСТВО</div><nav><a className="nav-item active"><Boxes size={17}/>Заказы <span className="nav-count">{filtered.length}</span></a><a className="nav-item"><Activity size={17}/>Аналитика</a><a className="nav-item"><WarehouseIcon size={17}/>Склады</a></nav><div className="sidebar-bottom"><span className="status-dot"/>Сервис подключён <span className="version">v0.9</span></div></aside>
 <main className="main"><header className="topbar"><div className="breadcrumb">Закупки <span>/</span> Рекомендации</div><div className="top-actions"><span className="today">{new Intl.DateTimeFormat('ru-RU',{day:'numeric',month:'long',year:'numeric'}).format(now)}</span><div className="avatar">МЗ</div></div></header>
 <div className="content"><div className="heading-row"><div><div className="eyebrow">УПРАВЛЕНИЕ ПОПОЛНЕНИЕМ <span className="live-dot"/></div><h1>Рекомендации к заказу</h1><p className="subtitle">Проверьте потребность, скорректируйте объём и подтвердите заказ вручную.</p></div><button className="primary run-button" onClick={run} disabled={busy}><RefreshCw size={16} className={busy?'spin':''}/>{busy?'Считаем…':'Рассчитать потребность'}</button></div>
 {isMock&&<div className="mock-banner"><CircleAlert size={16}/><span><b>Демо-режим</b> · Синтетические данные для разработки. Подключите API через <code>VITE_API_BASE_URL</code>.</span></div>}
 {error&&<div className="error-banner"><CircleAlert size={17}/>{error}<button onClick={()=>setError('')} aria-label="Закрыть">×</button></div>}
 <section className="filters card"><div className="filter-title"><SlidersHorizontal size={16}/> ПАРАМЕТРЫ РАСЧЁТА</div><label className="select-wrap"><WarehouseIcon size={15}/><select value={warehouse} onChange={e=>setWarehouse(e.target.value)}>{warehouses.map(x=><option key={x}>{x}</option>)}</select><ChevronDown size={14}/></label><label className="select-wrap"><Layers3 size={15}/><select value={category} onChange={e=>setCategory(e.target.value)}>{categories.map(x=><option key={x}>{x}</option>)}</select><ChevronDown size={14}/></label><span className="filter-hint">Фильтры применятся к следующему расчёту</span></section>
 <section className={`upload-panel card ${dragging?'is-dragging':''}`} onDragOver={e=>{e.preventDefault();setDragging(true)}} onDragLeave={()=>setDragging(false)} onDrop={e=>{e.preventDefault();setDragging(false);void handleUpload(e.dataTransfer.files[0])}}><div className="upload-icon"><FileSpreadsheet size={19}/></div><div className="upload-copy"><b>Загрузить отчёт партнёра</b><span>Excel-файл обновит исходные данные для следующего расчёта</span>{uploadMessage&&<em>{uploadMessage}</em>}</div><label className="btn btn-sm upload-button">{uploadBusy?'Загрузка…':'Выбрать Excel'}<input className="file-input file-input-sm" type="file" accept=".xlsx,.xls,.csv" hidden onChange={e=>{void handleUpload(e.target.files?.[0]);e.currentTarget.value=''}}/></label></section>
 <section className="metrics"><Metric label="ПОЗИЦИЙ К ЗАКАЗУ" value={String(filtered.length).padStart(2,'0')} sub={`${ready} из ${filtered.length} проверено`} icon={<ClipboardCheck/>} accent="green"/><Metric label="ЕДИНИЦ К ЗАКАЗУ" value={money.format(qty)} sub="По текущим рекомендациям" icon={<Boxes/>} accent="blue"/><Metric label="ТРЕБУЮТ ВНИМАНИЯ" value={String(urgent).padStart(2,'0')} sub="Критичный уровень остатка" icon={<CircleAlert/>} accent="orange"/></section>
 <div className="section-head"><div><h2>План пополнения</h2><p>Персональный план на основе актуальных остатков</p></div><div className="head-actions"><span className="updated"><span className="status-dot"/> Обновлено {new Intl.DateTimeFormat('ru-RU',{hour:'2-digit',minute:'2-digit'}).format(now)}</span><button className="quiet-button" onClick={exportCsv} disabled={!allApproved||exportBusy}><Download size={15}/>{exportBusy?'Готовим…':'Экспорт в 1С'}</button></div></div>
 <section className="table-card card"><div className="table-toolbar"><div className="tabs"><span className="tab active">Все позиции <b>{filtered.length}</b></span><span className="tab">На проверке <b>{filtered.filter(x=>!x.reviewed).length}</b></span><span className="tab">Подтверждены <b>{filtered.filter(x=>x.status==='approved').length}</b></span></div><div className="supplier-note"><span className="status-dot"/> Группировка по поставщику включена</div><form className="search-form" method="get"><label htmlFor="project-search">Search projects</label><div className="join"><input className="input input-sm join-item" id="project-search" name="q" type="search" placeholder="SKU или название"/><button className="btn btn-primary btn-sm join-item" type="submit">Search</button></div></form></div>
 <div className="table-scroll"><table><thead><tr><th>ПОЗИЦИЯ</th><th>ПОСТАВЩИК</th><th>ОСТАТОК / ТРЕНД</th><th>РЕКОМЕНДАЦИЯ</th><th>СРОЧНОСТЬ</th><th>ПРОВЕРКА</th></tr></thead><tbody>{Array.from(new Set(filtered.map(x=>x.supplier))).flatMap(supplier=>[<tr className="supplier-group" key={`${supplier}-group`}><td colSpan={6}><b>{supplier}</b><span>{filtered.filter(x=>x.supplier===supplier).length} позиции · {filtered.filter(x=>x.supplier===supplier).reduce((n,x)=>n+x.quantity,0)} ед.</span></td></tr>,...filtered.filter(x=>x.supplier===supplier).map(line=><tr key={line.id}><td><div className="product"><div className="product-icon"><PackageCheck size={17}/></div><div><b>{line.product}</b><span>{line.sku} <i>·</i> {line.category}</span></div></div></td><td><span className="supplier-name">{line.supplier}</span><span className="warehouse-name">{line.warehouse}</span></td><td><div className="stock"><b>{line.stock} <small>{line.unit}</small></b><span><Activity size={13}/> {line.monthlyUse}/мес. · {line.leadDays} дн.</span><div className="stock-track"><i style={{width:`${Math.min(100,line.stock/(line.monthlyUse||1)*100)}%`}}/></div></div></td><td><div className="quantity-control"><button aria-label="Уменьшить" disabled={line.status==='approved'} onClick={()=>patch(line.id,{quantity:Math.max(0,line.quantity-1)})}>−</button><input type="number" min="0" disabled={line.status==='approved'} value={line.quantity} onChange={e=>patch(line.id,{quantity:Math.max(0,Number(e.target.value))})}/><span>{line.unit}</span><button aria-label="Увеличить" disabled={line.status==='approved'} onClick={()=>patch(line.id,{quantity:line.quantity+1})}>+</button></div><span className="reason" title={line.justification + (line.seasonality ? ' · Сезонность: ' + line.seasonality : '') + (line.moq ? ' · MOQ: ' + line.moq : '')}>{line.justification}{line.seasonality ? ' · Сезонность: ' + line.seasonality : ''}{line.moq ? ' · MOQ: ' + line.moq : ''}</span></td><td><Badge className={`urgency ${line.urgency}`} variant={line.urgency==='critical'?'error':line.urgency==='soon'?'warning':'success'}><i/>{urgencyName[line.urgency]}</Badge></td><td><button className={`review ${line.reviewed?'checked':''}`} disabled={line.status==='approved'} onClick={()=>patch(line.id,{reviewed:!line.reviewed})}>{line.reviewed?<Check size={14}/>:<span className="check-empty"/>}{line.status==='approved'?'Подтверждено':line.reviewed?'Проверено':'Проверить'}</button>{line.status==='approved'&&<span className="approved-mini"><ShieldCheck size={12}/>Подтверждено</span>}</td></tr>)])}</tbody></table>{!filtered.length&&<div className="empty">По заданным фильтрам ничего не найдено.</div>}</div>
 <div className="table-footer"><span>Показано {filtered.length} позиций</span><span><Clock3 size={13}/> Данные расчёта: {now.toLocaleTimeString('ru-RU',{hour:'2-digit',minute:'2-digit'})}</span></div></section>
 <div className="lower-grid"><Card className="breakdown"><div className="panel-title"><div><h3>Распределение по категориям</h3><p>Структура объёма заказа</p></div><ArrowUpRight size={17}/></div><BarList data={categoriesSummary.map(item=>({name:`${item.name} · ${item.count} поз.`,value:item.units}))} valueFormatter={value=>`${money.format(value)} ед.`} sortOrder="descending" /></Card>
 <Card className="breakdown"><div className="panel-title"><div><h3>Поставщики</h3><p>Сводка рекомендованных заказов</p></div><ArrowUpRight size={17}/></div><BarList data={suppliers.map(item=>({name:`${item.name} · ${item.count} поз.`,value:item.units}))} valueFormatter={value=>`${money.format(value)} ед.`} sortOrder="descending" /></Card></div>
 <section className={`approval ${allApproved?'done':''}`}><div className="approval-icon">{allApproved?<ShieldCheck size={21}/>:<ClipboardCheck size={21}/>}</div><div className="approval-copy"><b>{allApproved?'Рекомендации подтверждены ответственным сотрудником':'Подтверждение менеджера по закупкам'}</b><span>{allApproved?'Backend зарегистрировал ручное согласование. Экспорт доступен; отправка поставщику не выполняется.':'Проверьте все строки и подтвердите заказ вручную. Это действие фиксирует согласование и открывает экспорт.'}</span></div><button className={allApproved?'quiet-button':'approve-button'} onClick={allApproved?exportCsv:approve} disabled={!filtered.length||filtered.some(x=>!x.reviewed)||busy||exportBusy}>{allApproved?<><FileSpreadsheet size={16}/>{exportBusy?'Готовим CSV…':'Скачать CSV для 1С'}</>:<><ShieldCheck size={16}/>{busy?'Подтверждаем…':'Подтвердить заказ'}</>}</button></section>
 <footer><span><ShieldCheck size={14}/> Отправка поставщикам отключена</span><span>Контур закупок <i>·</i> Инструмент планирования</span></footer></div></main></div>
}
function Metric({label,value,sub,icon,accent}:{label:string,value:string,sub:string,icon:React.ReactNode,accent:string}){return <Card className="metric"><div className={`metric-icon ${accent}`}>{icon}</div><div><span className="metric-label">{label}</span><div className="metric-value">{value}</div><span className="metric-sub">{sub}</span></div><ArrowUpRight className="metric-corner" size={15}/></Card>}
